#+TITLE: linux 安装java环境

** 早上重启了次centos ,然后查看jdk版本就。。。。。
centos 7 查看jdk 版本出现：

Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
1
2
目前这个错误也算是一个坑了 差点把自己埋了。。。。。
解决方法：就是先看看下载在目录下安装包的版本，jdk1.7 — jdk1.8
在centos7 当中操作指令集是不一样的 ，jdk1.7 查看版本号可以通过 java -Vand java --version 查看，
而jdk1.8 就得通过 java -version来查看版本号了

查看工具的操作指令集
工具名 -h
** 1、进入 Oracle 官方网站 下载合适的 JDK 版本，准备安装。
注意：这里需要下载 Linux 版本。这里以jdk-8u151-linux-x64.tar.gz为例，你下载的文件可能不是这个版本，这没关系，只要后缀(.tar.gz)一致即可。

2、创建目录

在/usr/目录下创建java目录，

mkdir /usr/local/java
cd /usr/local/java
把下载的文件 jdk-8u151-linux-x64.tar.gz 放在/usr/local/java/目录下。

3. 解压 JDK

tar -zxvf jdk-8u151-linux-x64.tar.gz

4. 设置环境变量

修改 vi /etc/profile

在 profile 文件中添加如下内容并保存：

set java environment
JAVA_HOME=/usr/local/java/jdk1.8.0_151        
JRE_HOME=/usr/local/java/jdk1.8.0_151/jre     
CLASS_PATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib
PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin
export JAVA_HOME JRE_HOME CLASS_PATH PATH
 

注意：其中 JAVA_HOME， JRE_HOME 请根据自己的实际安装路径及 JDK 版本配置。

让修改生效：

source /etc/profile

5. 测试
java -version

显示 java 版本信息，则说明 JDK 安装成功
